services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app # Mount the current directory into the container
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    environment:
      - DEBUG=True
      # Add any other necessary environment variables for DB or other services
      # - DATABASE_URL=postgres://user:password@db:5432/mydatabase
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
